version: "2"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgis/postgis:11-3.0
    restart: always
    volumes:
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: myapp,core
    ports:
      - "5432:5432"
